server:
  port: 9094

spring:
  application:
    name: NEWSFEED-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/saralportal
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: manishamusti@gmail.com
    password: jclzexkptkaimefd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
